openapi: 3.2.0
info:
  title: GitLab access_requests Internal Operations API
  version: v4
  description: Operations related to access requests
servers:
- url: https://gitlab.com
tags:
- name: internal_operations
  description: Operations about internal_operations
paths:
  /api/v4/integrations/slack/interactions:
    post:
      summary: Process Slack interaction events
      description: Processes interaction events from Slack
      responses:
        '201':
          description: Process Slack interaction events
      tags:
      - internal_operations
      operationId: postApiV4IntegrationsSlackInteractions
  /api/v4/integrations/slack/options:
    post:
      summary: Get Slack interactive component options
      description: Retrieves options for Slack interactive components
      responses:
        '201':
          description: Get Slack interactive component options
      tags:
      - internal_operations
      operationId: postApiV4IntegrationsSlackOptions
components:
  securitySchemes:
    access_token_header:
      type: apiKey
      name: PRIVATE-TOKEN
      in: header
    access_token_query:
      type: apiKey
      name: private_token
      in: query
