openapi: 3.2.0
info:
  title: GitLab access_requests Ldap API
  version: v4
  description: Operations related to access requests
servers:
- url: https://gitlab.com
tags:
- name: ldap
  description: Operations about ldaps
paths:
  /api/v4/groups/{id}/ldap_sync:
    post:
      description: Sync a group with LDAP.
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        '201':
          description: Sync a group with LDAP.
      tags:
      - ldap
      operationId: postApiV4GroupsIdLdapSync
components:
  securitySchemes:
    access_token_header:
      type: apiKey
      name: PRIVATE-TOKEN
      in: header
    access_token_query:
      type: apiKey
      name: private_token
      in: query
