generated: '2026-07-11'
method: derived
source: openapi/gitlab-ci-openapi.yml
summary:
  types:
  - apiKey
  api_key_in:
  - header
  - query
schemes:
- name: access_token_header
  type: apiKey
  in: header
  parameter: PRIVATE-TOKEN
  sources:
  - openapi/gitlab-ci-openapi.yml
- name: access_token_query
  type: apiKey
  in: query
  parameter: private_token
  sources:
  - openapi/gitlab-ci-openapi.yml
